create table if not exists submissions (
  id bigint generated by default as identity primary key,
  faculty_email text not null,
  course_title text not null,
  offering_department text not null check (offering_department in ('MA', 'CS', 'UZ')),
  target_department text not null check (target_department in ('CSE', 'ECE', 'ME', 'BT', 'EEE', 'AIML')),
  semester integer not null check (semester between 1 and 8),
  credit_category text not null check (credit_category in ('0', '2', '4', '5')),
  raw_course_content text not null,
  text_books text not null,
  reference_books text not null default '',
  preferred_tools text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists refined_submissions (
  id bigint generated by default as identity primary key,
  submission_id bigint not null unique references submissions(id) on delete cascade,
  semester integer not null check (semester between 1 and 8),
  course_code text not null default '',
  course_title text not null,
  program text not null,
  lecture_hours integer not null default 0,
  tutorial_hours integer not null default 0,
  practical_hours integer not null default 0,
  self_study integer not null default 0,
  credits integer not null default 0,
  course_type text not null,
  tools_languages text not null default '',
  desirable_knowledge text not null default '',
  prelude text not null default '',
  objectives text[] not null default '{}',
  course_outcomes text[] not null default '{}',
  units jsonb not null default '[]'::jsonb check (jsonb_typeof(units) = 'array'),
  lab_experiments text[] not null default '{}',
  text_books text[] not null default '{}',
  reference_books text[] not null default '{}',
  status text not null default 'refined',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists curriculum_versions (
  id bigint generated by default as identity primary key,
  name text not null,
  program text not null,
  academic_year text not null,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists finalized_submissions (
  id bigint generated by default as identity primary key,
  curriculum_version_id bigint not null references curriculum_versions(id) on delete cascade,
  refined_id bigint not null references refined_submissions(id) on delete restrict,
  course_json jsonb not null check (jsonb_typeof(course_json) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (curriculum_version_id, refined_id)
);

create table if not exists agent_document_drafts (
  id bigint generated by default as identity primary key,
  curriculum_version_id bigint references curriculum_versions(id) on delete set null,
  uploaded_document_id text not null default '',
  diff_summary jsonb not null default '{}'::jsonb check (jsonb_typeof(diff_summary) = 'object'),
  change_reason text not null default '',
  status text not null default 'proposed' check (status in ('proposed', 'blocked', 'approved', 'rejected', 'applied')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists agent_drafts (
  id bigint generated by default as identity primary key,
  refined_id bigint not null references refined_submissions(id) on delete cascade,
  document_draft_id bigint references agent_document_drafts(id) on delete cascade,
  base_refined_json jsonb not null check (jsonb_typeof(base_refined_json) = 'object'),
  proposed_json jsonb not null check (jsonb_typeof(proposed_json) = 'object'),
  json_patch jsonb not null default '[]'::jsonb check (jsonb_typeof(json_patch) = 'array'),
  diff_summary jsonb not null default '{}'::jsonb check (jsonb_typeof(diff_summary) = 'object'),
  change_reason text not null default '',
  status text not null default 'proposed' check (status in ('proposed', 'blocked', 'approved', 'rejected', 'applied')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists course_revision_history (
  id bigint generated by default as identity primary key,
  refined_id bigint not null references refined_submissions(id) on delete cascade,
  agent_draft_id bigint references agent_drafts(id) on delete set null,
  source text not null default 'agent_draft',
  previous_json jsonb not null check (jsonb_typeof(previous_json) = 'object'),
  next_json jsonb not null check (jsonb_typeof(next_json) = 'object'),
  json_patch jsonb not null default '[]'::jsonb check (jsonb_typeof(json_patch) = 'array'),
  diff_summary jsonb not null default '{}'::jsonb check (jsonb_typeof(diff_summary) = 'object'),
  change_reason text not null default '',
  changed_by text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists submissions_semester_idx on submissions (semester);
create index if not exists submissions_status_idx on submissions (status);
create index if not exists refined_submissions_semester_idx on refined_submissions (semester);
create index if not exists agent_drafts_refined_id_idx on agent_drafts (refined_id);
create index if not exists agent_drafts_document_draft_id_idx on agent_drafts (document_draft_id);
create index if not exists agent_drafts_status_idx on agent_drafts (status);
create index if not exists agent_document_drafts_status_idx on agent_document_drafts (status);
create index if not exists finalized_submissions_curriculum_version_idx on finalized_submissions (curriculum_version_id);
create index if not exists course_revision_history_refined_id_idx on course_revision_history (refined_id);
